name: AWS Infrastructure
on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_CLOUD_WORKSPACE: ${{ vars.TF_WORKSPACE }}

jobs:
  terraform-fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform -chdir=./terraform fmt -check -diff

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Plan
        run: terraform -chdir=./terraform plan

  terraform-init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=./terraform init

  terraform-apply:
    name: Terraform Apply
    needs: [terraform-fmt, terraform-plan, terraform-init]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve

  terraform-tests:
    name: Terraform Tests
    needs: [terraform-fmt, terraform-plan, terraform-init]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Terraform tests
        run: python -m unittest tests/test_terraform.py
