name: AWS Infrastructure
on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_CLOUD_WORKSPACE: ${{ vars.TF_WORKSPACE }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Terraform Init
        run: terraform -chdir=./terraform init

      - name: Terraform Format
        run: terraform -chdir=./terraform fmt -check -diff

      - name: Terraform Tests
        run: python -m unittest tests/test_terraform.py

      - name: Terraform Plan
        run: terraform -chdir=./terraform plan -out=./terraform/tf.plan

      - uses: actions/upload-artifact@master
        with:
          name: tf-plan
          path: ./terraform/tf.plan

  terraform-apply:
    name: Terraform Apply
    needs: [terraform-plan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: tf-plan
          path: ./terraform/tf.plan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform -chdir=./terraform init

      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve