name: AWS Infrastructure
on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_CLOUD_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Terraform Init
        run: terraform -chdir=./terraform init

      - name: Terraform Format
        run: terraform -chdir=./terraform fmt -check -diff

      # - name: Terraform Tests
      #   run: python -m unittest tests/test_terraform.py

      - name: Terraform Plan
        run: terraform -chdir=./terraform plan

  terraform-apply:
    name: Terraform Apply
    needs: [terraform-plan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform -chdir=./terraform init

      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve